# Generated by Django 5.1 on 2024-08-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
