# Generated by Django 5.1 on 2024-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_booking_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
